library("phyloseq", lib.loc="/data1/local/lib/R/site-library")
library("ggplot2", lib.loc="/data1/local/lib/R/site-library")
biom=("/data1/home/kvaviko/Basecalls/Microbiom/16_S.biom")
phyloseq=import_biom(biom)
phyloseq
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_Rank2.png", width = 1000, height =1200,res=75)
plot_bar(phyloseq, fill="Rank2")
dev.off()
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_Rank5.png", width = 1000, height =1500,res=75)
plot_bar(phyloseq, fill="Rank5")
dev.off()
library("ape", lib.loc="/data1/local/lib/R/site-library")
random_tree = rtree(ntaxa(phyloseq), rooted = TRUE, tip.label=taxa_names(phyloseq))
phyloseq_tree=merge_phyloseq(phyloseq,random_tree)
phyloseq_tree
sampledata=read.csv("/data1/home/kvaviko/Basecalls/Microbiom/sampledata", header=TRUE, sep="")
sampledata
samp=sample_data(data.frame(sampledata,row.names = sample_names(phyloseq_tree)))
samp
phyloseq_final=merge_phyloseq(phyloseq_tree,samp)
phyloseq_final
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_Rank5_Extraction.png", width = 1000, height =1500,res=75)
plot_bar(phyloseq_final, x="Extraction_Method", fill="Rank5")
dev.off()
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_Rank5_facetgrid1.png",width = 1000, height =1500,res=75)
p=plot_bar(phyloseq_final,"Rank2",fill="Rank5", facet_grid=~Extraction_Method)
p + geom_bar(aes(color=Rank5, fill=Rank5), stat="identity", position="stack")+theme(axis.text.x=element_text(angle=-90,vjust=0.5,size=8,face="bold"))+theme(legend.position="right") + theme(legend.text = element_text(colour="blue", size=8, face="bold"))
diagadds = phyloseq_to_deseq2(phyloseq_final, ~ Extraction_Method)
diagadds = DESeq(diagadds, test="Wald", fitType="parametric")
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_Volcano_Mean.png")
plotMA(diagadds,ylim=c(-2,2),main="DESeq2")
dev.off()
res = results(diagadds, cooksCutoff = FALSE)
res<-res[order(res$padj),]
sigtab = res[order(res$padj), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(emory_pilot)[rownames(sigtab), ], "matrix"))
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(phyloseq_final)[rownames(sigtab), ], "matrix"))
scale_fill_discrete <- function(palname = "Set1", ...) { scale_fill_brewer(palette = palname, ...) }
x = tapply(sigtab$log2FoldChange, sigtab$Rank2, function(x) max(x))
x = sort(x, TRUE)
sigtab$Rank2 = factor(as.character(sigtab$Rank2), levels=names(x))
x = tapply(sigtab$log2FoldChange, sigtab$Rank5, function(x) max(x))
x = sort(x, TRUE)
sigtab$Rank5 = factor(as.character(sigtab$Rank5), levels=names(x))
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_FoldChange.png")
ggplot(sigtab, aes(x=Rank5, y=log2FoldChange, color=Rank2)) + geom_point(size=2) + theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.3))
dev.off()
physeqdf <- psmelt(phyloseq_final)
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_psmelt_Rank2.png",width = 1000, height =1200,res=75)
p1=ggplot(physeqdf,aes(x=Sample,y=Abundance,fill=Rank2))
p1+geom_bar(stat="identity",position="fill")+scale_fill_manual(values = c("grey26","royalblue","chartreuse3","red","darkorange","cyan2", "darkgreen","blue4", "yellow1", "violetred", "deepskyblue", "mediumorchid3","#89C5DA", "#DA5724", "#74D944", "#C84248","#673770", "#D3D93E", "#38333E", "#508578","#D7C1B1", "#689030", "#AD6F3B", "#CD9BCD","#D14285", "#6DDE88", "#652926", "#7FDCC0", "#8569D5", "#5E738F", "#D1A33D","#8A7C64", "#599861"))+theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
dev.off()
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_psmelt_Rank2_nofill.png",width = 1000, height =1200,res=75)
p1+geom_bar(stat="identity")+scale_fill_manual(values = c("grey26","royalblue","chartreuse3","red","darkorange","cyan2", "darkgreen","blue4", "yellow1", "violetred", "deepskyblue", "mediumorchid3","#89C5DA", "#DA5724", "#74D944", "#C84248","#673770", "#D3D93E", "#38333E", "#508578","#D7C1B1", "#689030", "#AD6F3B", "#CD9BCD","#D14285", "#6DDE88", "#652926", "#7FDCC0", "#8569D5", "#5E738F", "#D1A33D","#8A7C64", "#599861"))+theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
library("doParallel")
registerDoParallel(cores=7)
GP.wufmds <- ordinate(phyloseq_final, "PCoA", distance="unifrac", weighted=TRUE, parallel=TRUE)
p2 = plot_ordination(phyloseq_final, GP.wufmds, color="Extraction_Method", label="sample")
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_Unifrac_PCA.png",width = 900, height =900,res=100)
p2+ geom_point(size=2) + geom_line()
dev.off()
p3 = plot_ordination(phyloseq_final, GP.wufmds, color="Patient_ID", label="sample")
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_Unifrac_PCA_ID.png",width = 900, height =900,res=100)
p3+ geom_point(size=2) + geom_line()
dev.off()
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_alpha.png",width = 1000, height =1200,res=75)
p4= plot_richness(phyloseq_final, x = "sample", color = "Extraction_Method", measures = c("Chao1", "Shannon"))
p4 + geom_point(size = 5, alpha = 0.7)
dev.off()
png("/data1/home/kvaviko/Basecalls/Microbiom/16_S_alpha_ID.png",width = 1000, height =1200,res=75)
p5 = plot_richness(phyloseq_final, x = "sample", color = "Patient_ID", measures = c("Chao1", "Shannon"))
p5 + geom_point(size = 5, alpha = 0.7)
dev.off()
